name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: StruggleYang/VuePagesAction@2.0.0
      with:
        username: 'walamana'
        reponame: 'werwolf-telegram'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
