name: Build Vue
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Vue
      run: |
            npm ci;
            npm run build;
            cd ..
            ls
      shell: bash
    - name: Upload to Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: './dist'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
